load("@rules_java//java:defs.bzl", "java_binary")

package(default_visibility = ["//visibility:public"])

java_binary(
    name = "jlox",
    main_class = "kat.jens.lox.Lox",
    srcs = glob(["kat/jens/lox/*.java"]),
)
